### ISSUE TITLE
heurística do frictionless.yaml no github workflow

### ISSUE THREAD

**Issue by Andrelamor** [transparencia-mg/datapackage-reprex#1]
Os resultados das validações com as 2 ferramentas (goodtables X frictionless.yaml) estão differindo. Verificar quais configurações devem ser mais adequadas para o arquivo yaml em https://repository.frictionlessdata.io/docs/inquiries

Tentativa de apontar pro datapackage não funcionou em: https://github.com/dados-mg/doacoes-comodatos-amigo-estado-mg/actions/runs/886428718

* exemplos

1. doações-selo-amigo-estado-mg:

parece que o frictionless.yaml não está validando os arquivos da raiz da pasta data, mas somente os arquivos da subpasta data-raw; o goodtables pegou erro de validação em https://goodtables.io/github/dados-mg/doacoes-comodatos-amigo-estado-mg/jobs/52 que passou batido em https://repository.frictionlessdata.io/report/?user=dados-mg&repo=doacoes-comodatos-amigo-estado-mg&flow=frictionless&run=886385818

2. termos-parceria-contratos-gestao:

https://goodtables.io/github/dados-mg/termos-parceria-contratos-gestao/jobs/59

https://repository.frictionlessdata.io/report/?user=dados-mg&repo=termos-parceria-contratos-gestao&flow=frictionless&run=885888283 (não pegou células de valor vazio em colunas com required constraints)

**Comment by Andrelamor** [comment]
o fricitonless.yaml não lê os parâmetros constantes no ``datapackage.json``:

https://repository.frictionlessdata.io/report/?user=transparencia-mg&repo=mapa-consultas-portal-transparencia&flow=frictionless&run=897038880

X 

https://goodtables.io/github/transparencia-mg/mapa-consultas-portal-transparencia/jobs/88

**Comment by gabrielbdornas** [comment]
@Andrelamor, ainda faz sentido este issue? Acredito que não.

Acho que consegui o resultado esperado para este tipo de problema aqui:

https://github.com/transparencia-mg/dataset-template/blob/61ad1d2e3fdff7236ad89be52928bbfedc64e021/.github/frictionless.yaml#L1-L3

Vou fechar o issue. Caso você não concorde voltamos a abrí-lo.
